from .routing import ROUTE_CORPUS_PROMPT, ROUTE_CHAPTER_NUMBER_and_SPLIT_QUES_PROMPT, ROUTE_INTENT_PROMPT


__all__ = [
    'ROUTE_CORPUS_PROMPT',
    'ROUTE_CHAPTER_NUMBER_and_SPLIT_QUES_PROMPT',
    'ROUTE_INTENT_PROMPT',
]