INTENT_ROUTES = {
    "chat": [
        "hi", "hello", "chào", "alo", "ok", "cảm ơn",
    ],
    "summary": [
        "tóm tắt", "tóm lược", "viết tóm tắt", "ý chính",
        "tóm tắt",
        "tóm lược",
        "viết tóm tắt",
        "tóm tắt giúp mình",
        "tóm tắt giúp tôi",
        "tóm tắt lại",
        "tóm tắt nội dung",
        "tóm tắt phần này",
        "tóm tắt đoạn này",
        "ý chính",
        "ý cơ bản",
        "ý trọng tâm",
        "nội dung chính",
        "các ý chính",
        "các điểm chính",
        "trọng tâm bài",
        "phần quan trọng",
        "gạch đầu dòng",
        "liệt kê ý chính",
        "tóm tắt theo gạch đầu dòng",
        "tóm tắt dạng sơ đồ",
        "tóm tắt dạng bảng",
        "tóm tắt ngắn gọn",
        "tóm tắt súc tích",
        "rút gọn nội dung",
        "viết ngắn lại",
        "viết lại cho dễ hiểu",
        "viết lại ngắn gọn",
        "lược bỏ chi tiết",
        "tóm lại là gì",
        "nói ngắn gọn lại",
        "giải thích ngắn gọn",
        'nêu ngắn gọn'
        "cho mình bản tóm tắt",
        "cho mình ý chính",
    ],
    "study": [
        "trình bày", "giải thích", "phân tích",
        "so sánh", "đánh giá", "nêu", "liệt kê",
        "vì sao", "như thế nào", "ý nghĩa", "kết quả",
        "học bài", "giúp tôi học", "ôn tập",
        "làm bài", "học môn", "giúp mình học",
        "học bài",
        "giúp tôi học",
        "giúp mình học",
        "nhờ bạn dạy",
        "nhờ bạn giảng",
        "học với mình",
        "học cùng mình",
        "học giúp mình",
        "dạy mình với",
        "chỉ mình với",
        "ôn tập",
        "ôn bài",
        "ôn thi",
        "ôn kiểm tra",
        "ôn lại kiến thức",
        "chuẩn bị thi",
        "chuẩn bị kiểm tra",
        "xem lại bài",
        "học lại phần này",
        "làm bài",
        "làm bài tập",
        "giúp làm bài",
        "giúp mình làm bài",
        "làm bài này",
        "giải bài",
        "giải giúp bài này",
        "bài này làm sao",
        "bài này khó quá",
        "học môn",
        "học môn này",
        "học môn đó",
        "học phần này",
        "học chương này",
        "học bài này",
        "học phần này với",
        "không hiểu bài",
        "chưa hiểu bài",
        "mình chưa hiểu",
        "mình không hiểu",
        "học hoài không hiểu",
        "bài này rối quá",
        "bài này khó hiểu",
        "giải thích giúp mình",
    ],
}
GENERIC_STUDY_PHRASES = [
    "kết quả", "ý nghĩa", "nguyên nhân", "bài học", "bài học kinh nghiệm",
    "nội dung", "vai trò", "tác động", "đặc điểm"
]

ENTITY_HINTS = [
    "đại hội", "cương lĩnh", "đổi mới", "toàn quốc kháng chiến",
    "kháng chiến", "1945", "1954", "1975", "1986", "1991", "2011"
]
QUES_LSD = {
    "lsd": [
        "Hoàn cảnh Việt Nam sau 2/9/1945 như thế nào?",
        "Chủ trương của Đảng nhằm bảo vệ và giữ vững chính quyền cách mạng (9/1945–12/1946) là gì?",
        "Toàn quốc kháng chiến diễn ra như thế nào?",
        "Ý nghĩa của toàn quốc kháng chiến là gì?",
        "Nội dung đường lối kháng chiến chống Pháp (1946–1954) là gì?",
        "Sự phát huy của đường lối đó trong kháng chiến chống Mỹ là gì?",
        "Nội dung đường lối cách mạng dân tộc dân chủ nhân dân tại Đại hội II (2/1951) là gì?",
        "Đường lối cách mạng hai miền được thể hiện trong nội dung Đại hội III như thế nào?",
        "Kết quả của Đảng trong kháng chiến chống Pháp (1945–1954) là gì?",
        "Ý nghĩa của Đảng trong kháng chiến chống Pháp (1945–1954) là gì?",
        "Bài học kinh nghiệm của Đảng trong kháng chiến chống Pháp (1945–1954) là gì?",
        "Kết quả của Đảng trong kháng chiến chống Mỹ (1954–1975) là gì?",
        "Ý nghĩa của Đảng trong kháng chiến chống Mỹ (1954–1975) là gì?",
        "Bài học kinh nghiệm của Đảng trong kháng chiến chống Mỹ (1954–1975) là gì?",
        "Hoàn cảnh Việt Nam sau 2/9/1945 như thế nào?",
        "Toàn quốc kháng chiến diễn ra như thế nào?",
        "Ý nghĩa của toàn quốc kháng chiến là gì?",
        "Nội dung đường lối kháng chiến chống Pháp (1946–1954) là gì?",
        "Sự phát huy của đường lối đó trong kháng chiến chống Mỹ là gì?",
        "Nội dung đường lối cách mạng dân tộc dân chủ nhân dân tại Đại hội II (2/1951) là gì?",
        "Đường lối cách mạng hai miền đư ợc thể hiện trong Đại hội III như thế nào?",
        "Kết quả của Đảng trong kháng chiến chống Pháp (1945–1954) là gì?",
        "Ý nghĩa của Đảng trong kháng chiến chống Pháp (1945–1954) là gì?",
        "Bài học kinh nghiệm của Đảng trong kháng chiến chống Pháp (1945–1954) là gì?",
        "Kết quả của Đảng trong kháng chiến chống Mỹ (1954–1975) là gì?",
        "Ý nghĩa của Đảng trong kháng chiến chống Mỹ (1954–1975) là gì?",
        "Bài học kinh nghiệm của Đảng trong kháng chiến chống Mỹ (1954–1975) là gì?",
        "Khái quát quá trình xây dựng CNXH trong cả nước đến năm 1986 như thế nào?",
        "Quá trình tìm con đường đổi mới đất nước đến năm 1986 diễn ra như thế nào?",
        "Nội dung Đường lối đổi mới của Đại hội VI (12/1986) là gì?",
        "Nội dung Đại hội VII là gì?",
        "Ý nghĩa của Đại hội VII là gì?",
        "Những điểm đổi mới ở Đại hội VII là gì?",
        "Nội dung Đại hội VIII là gì?",
        "Ý nghĩa của Đại hội VIII là gì?",
        "Những điểm đổi mới ở Đại hội VIII là gì?",
        "Nội dung Đại hội IX là gì?",
        "Ý nghĩa của Đại hội IX là gì?",
        "Những điểm đổi mới ở Đại hội IX là gì?",
        "Nội dung Đại hội X là gì?",
        "Ý nghĩa của Đại hội X là gì?",
        "Những điểm đổi mới ở Đại hội X là gì?",
        "Nội dung Đại hội XI là gì?",
        "Ý nghĩa của Đại hội XI là gì?",
        "Những điểm đổi mới ở Đại hội XI là gì?",
        "Nội dung Đại hội XII là gì?",
        "Ý nghĩa của Đại hội XII là gì?",
        "Những điểm đổi mới ở Đại hội XII là gì?",
        "Nội dung Cương lĩnh xây dựng đất nước thời kỳ quá độ lên CNXH năm 1991 là gì?",
        "Nội dung Cương lĩnh năm 2011 là gì?",
        "So sánh Cương lĩnh 1991 và 2011?",
        "Thành tựu của Đảng trong sự nghiệp đổi mới là gì?",
        "Ý nghĩa lịch sử của sự nghiệp đổi mới là gì?",
        "Kinh nghiệm lãnh đạo của Đảng trong sự nghiệp đổi mới là gì?",
    ],
    "ktct": [

    ],
    "triet": [
        "",
    ],
}
DOC_ROUTES = {
    "lsd": [
        # 
        "chủ trương"
        "chính quyền cách mạng"
        "Cương lĩnh chính trị đầu tiên"
        "giai cấp và mâu thuẫn",
        "sự chuyển hướng",
        "hội nghị trung ương 6",
        "hội nghị trung ương 7",
        "hội nghị trung ương 8",
        #
        "cách mạng", "đảng cộng sản", "hồ chí minh", "kháng chiến",
        "giành chính quyền", "đại hội", "miền bắc", "miền nam",
        "chống mỹ", "đổi mới",
        "Việt Nam sau 2/9/1945",
        "hoàn cảnh lịch sử",
        "toàn quốc kháng chiến",
        "ý nghĩa toàn quốc kháng chiến",
        "kháng chiến chống Pháp",
        "đường lối kháng chiến chống Pháp",
        "kháng chiến toàn dân",
        "kháng chiến toàn diện",
        "kháng chiến lâu dài",
        "tự lực cánh sinh",
        "tranh thủ sự ủng hộ quốc tế",
        "kháng chiến chống Mỹ",
        "phát huy đường lối kháng chiến",
        "giải phóng miền Nam",
        "thống nhất đất nước",
        "cách mạng dân tộc dân chủ nhân dân",
        "Đại hội II",
        "đường lối cách mạng hai miền",
        "Đại hội III",
        "kết quả kháng chiến chống Pháp",
        "ý nghĩa kháng chiến chống Pháp",
        "bài học kinh nghiệm kháng chiến chống Pháp",
        "kết quả kháng chiến chống Mỹ",
        "ý nghĩa kháng chiến chống Mỹ",
        "bài học kinh nghiệm kháng chiến chống Mỹ",
        "xây dựng CNXH",
        "cả nước đi lên CNXH",
        "tìm con đường đổi mới",
        "đổi mới đất nước",
        "Đường lối đổi mới",
        "Đại hội VI",
        "Đại hội VII",
        "Đại hội VIII",
        "Đại hội IX",
        "Đại hội X",
        "Đại hội XI",
        "Đại hội XII",
        "nội dung Đại hội",
        "ý nghĩa Đại hội",
        "điểm đổi mới của Đại hội",
        "Cương lĩnh 1991",
        "Cương lĩnh 2011",
        "so sánh Cương lĩnh 1991 và 2011",
        "thành tựu đổi mới",
        "ý nghĩa lịch sử đổi mới",
        "kinh nghiệm lãnh đạo đổi mới",
        "vai trò lãnh đạo của Đảng",
        "Đảng Cộng sản Việt Nam"

    ],
    "ktct": [
        "hàng hóa", "thị trường", "giá trị", "lao động",
        "cung cầu", "tiền tệ", "dịch vụ", "cổ phiếu",
        "trái phiếu", "kinh tế thị trường",
        # (có thể thêm giá trị thặng dư, tư bản, quan hệ sản xuất… nếu muốn)
    ],
    "triet": [
        "vật chất", "ý thức", "chủ nghĩa duy vật", "chủ nghĩa duy tâm",
        "chủ nghĩa siêu hình", "phép biện chứng",
        "chủ nghĩa duy vật biện chứng", "chủ nghĩa duy vật lịch sử",

        "mối liên hệ phổ biến", "sự phát triển", "phủ định biện chứng",
        "đấu tranh của các mặt đối lập", "nguyên nhân kết quả",
        "tất nhiên ngẫu nhiên", "bản chất hiện tượng",
        "khả năng hiện thực",

        "lượng", "chất", "điểm nút", "bước nhảy",

        "nhận thức", "thực tiễn", "chân lý", "tiêu chuẩn của chân lý",

        "tồn tại xã hội", "ý thức xã hội",
        "lực lượng sản xuất", "quan hệ sản xuất",
        "phương thức sản xuất", "cơ sở hạ tầng",
        "kiến trúc thượng tầng", "hình thái kinh tế xã hội",

        "đấu tranh giai cấp", "nhà nước", "cách mạng xã hội",

        "con người", "bản chất con người", "lao động",
        "tha hóa", "tự do", "vai trò quần chúng nhân dân",
        "vai trò cá nhân", "động lực phát triển xã hội"
    ],
}




